<?php

namespace CommonBundle\Repository\Counting;

use Doctrine\ORM\EntityRepository;

/**
 * Counting
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Counting extends EntityRepository
{
}
