<?php

namespace CommonBundle\Repository\Counting;

use Doctrine\ORM\EntityRepository;

/**
 * MoneyUnit
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoneyUnit extends EntityRepository
{
    public function findAll()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('m')
            ->from('CommonBundle\Entity\Counting\MoneyUnit', 'm')
            ->orderBy('m.value', 'ASC')
            ->getQuery()
            ->getResult();

        return $resultSet;
    }
}
