<?php

namespace CommonBundle\Repository\Counting;

use Doctrine\ORM\EntityRepository;

/**
 * NumberMoneyUnit
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumberMoneyUnit extends EntityRepository
{
}