<?php

namespace MistDoctrine\Proxy\__CG__\CommonBundle\Entity\Stock;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Purchase extends \CommonBundle\Entity\Stock\Purchase implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getItem()
    {
        $this->__load();
        return parent::getItem();
    }

    public function getPrice()
    {
        $this->__load();
        return parent::getPrice();
    }

    public function getNumber()
    {
        $this->__load();
        return parent::getNumber();
    }

    public function getDate()
    {
        $this->__load();
        return parent::getDate();
    }

    public function getTimestamp()
    {
        $this->__load();
        return parent::getTimestamp();
    }

    public function getSales()
    {
        $this->__load();
        return parent::getSales();
    }

    public function getNumberSold()
    {
        $this->__load();
        return parent::getNumberSold();
    }

    public function getNumberInStock()
    {
        $this->__load();
        return parent::getNumberInStock();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'price', 'number', 'date', 'timestamp', 'item', 'sales');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}