<?php

namespace CommonBundle\Repository\Activity;

use Doctrine\ORM\EntityRepository;

/**
 * Activity
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Activity extends EntityRepository
{
    public function findAll()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('a')
            ->from('CommonBundle\Entity\Activity\Activity', 'a')
            ->orderBy('a.date', 'ASC')
            ->getQuery()
            ->getResult();

        return $resultSet;
    }
}