<?php

namespace CommonBundle\Repository\Activity;

use Doctrine\ORM\EntityRepository;

/**
 * Expense
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Expense extends EntityRepository
{
}