<?php

namespace CommonBundle\Repository\Activity;

use Doctrine\ORM\EntityRepository;

/**
 * Revenue
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Revenue extends EntityRepository
{
}
