<?php

namespace CommonBundle\Repository\Activity;

use Doctrine\ORM\EntityRepository;

/**
 * TransactionType
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionType extends EntityRepository
{
    public function findAll()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('t')
            ->from('CommonBundle\Entity\Activity\TransactionType', 't')
            ->orderBy('t.name', 'ASC')
            ->getQuery()
            ->getResult();

        return $resultSet;
    }
}