<?php

namespace CommonBundle\Repository\Stock;

use Doctrine\ORM\EntityRepository;

/**
 * Item
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Item extends EntityRepository
{
    public function findAll()
    {
        $query = $this->_em->createQueryBuilder();
        $resultSet = $query->select('i')
            ->from('CommonBundle\Entity\Stock\Item', 'i')
            ->orderBy('i.name', 'ASC')
            ->getQuery()
            ->getResult();

        return $resultSet;
    }
}