<?php

namespace CommonBundle\Repository\Stock;

use Doctrine\ORM\EntityRepository;

/**
 * Purchase
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Purchase extends EntityRepository
{
}